linstor_exec: vmm: restore_linstor_un save_linstor_un

diff --git a/vmm/kvm/restore_linstor_un b/vmm/kvm/restore_linstor_un
--- a/vmm/kvm/restore_linstor_un
+++ b/vmm/kvm/restore_linstor_un
@@ -70,6 +70,15 @@ STORAGE_POOL="${XPATH_ELEMENTS[j++]}"
 DISKLESS_POOL="${XPATH_ELEMENTS[j++]:-DfltDisklessStorPool}"
 ENCRYPTION="${XPATH_ELEMENTS[j++]}"
 
+SRC_RES="one-vm-${VM_ID}-checkpoint"
+SRC_DEV="/dev/drbd/by-res/${SRC_RES}/0"
+SRC_XML=${SRC_PATH}.xml
+DS_ID=$(echo $SRC_PATH | $AWK -F/ '{print $(NF-2)}')
+DS_LOCATION=$(echo $SRC_PATH | $SED 's|\(/[^/]*\)\{2\}$||g')
+DS_LOCATION_NON_DOUBLE_SLASH=$(echo "$DS_LOCATION" | $SED 's|//|/|g')
+
+#-------------------------------------------------------------------------------
+# TM_MAD is not 'linstor_un'
 #-------------------------------------------------------------------------------
 
 if [ "$TM_MAD" != "linstor_un" ]; then
@@ -77,6 +86,8 @@ if [ "$TM_MAD" != "linstor_un" ]; then
     exit $?
 fi
 
+#-------------------------------------------------------------------------------
+# TM_MAD is 'linstor_un'
 #-------------------------------------------------------------------------------
 
 source ${DRIVER_PATH}/../../etc/vmm/kvm/kvmrc
@@ -86,20 +97,23 @@ source ${DRIVER_PATH}/../../datastore/linstor_un/linstor_utils.sh
 
 linstor_load_keys
 
-SRC_RES="one-vm-${VM_ID}-checkpoint"
-SRC_DEV="/dev/drbd/by-res/${SRC_RES}/0"
-SRC_XML=${SRC_PATH}.xml
-DS_ID=$(echo $SRC_PATH | $AWK -F/ '{print $(NF-2)}')
-DS_LOCATION=$(echo $SRC_PATH | $SED 's|\(/[^/]*\)\{2\}$||g')
-DS_LOCATION_NON_DOUBLE_SLASH=$(echo "$DS_LOCATION" | $SED 's|//|/|g')
+# Load cleanup trap
+trap linstor_cleanup_trap EXIT
 
-linstor_attach_volume "$DST_HOST" "$SRC_RES" "$DISKLESS_POOL"
+# Attach diskless resource for DST_RES on DST_HOST
+SRC_RES_HOSTS=$(linstor_get_hosts_for_res "$SRC_RES")
+if ! [[ " $SRC_RES_HOSTS " =~ " $DST_HOST " ]]; then
+    linstor_exec_and_log \
+        "resource create -s $DISKLESS_POOL $DST_HOST $SRC_RES"
+fi
 
-ssh_exec_and_log    "$DST_HOST" "$QEMU_IMG convert -O raw $SRC_DEV $SRC_PATH" \
-                    "Error importing $SRC_DEV on $DST_HOST"
+ssh_exec_and_log "$DST_HOST" \
+    "$QEMU_IMG convert -O raw $SRC_DEV $SRC_PATH" \
+    "Error importing $SRC_DEV on $DST_HOST"
 
-exec_and_log "$LINSTOR resource-definition delete $SRC_RES --async" \
-             "Error deleting $SRC_RES"
+exec_and_log \
+    "$LINSTOR resource-definition delete $SRC_RES --async" \
+    "Error deleting $SRC_RES"
 
 RECALCULATE_CMD=$(cat <<EOF
 set -e -o pipefail
@@ -127,7 +141,8 @@ ssh_exec_and_log "$DST_HOST" "$RECALCULATE_CMD" \
 # We retry 3 times before failing completely.
 
 function restore_domain {
-    ssh_exec_and_log "$DST_HOST" "virsh --connect $LIBVIRT_URI restore $SRC_PATH --xml $SRC_XML" \
+    ssh_exec_and_log "$DST_HOST" \
+        "virsh --connect $LIBVIRT_URI restore $SRC_PATH --xml $SRC_XML" \
         "Could not restore from $SRC_PATH on $DST_HOST"
 }
 
@@ -137,7 +152,8 @@ if [ $? -ne 0 ]; then
     exit 1
 fi
 
-ssh_exec_and_log_no_error "$DST_HOST" "rm $SRC_PATH $SRC_XML" \
+ssh_exec_and_log_no_error "$DST_HOST" \
+    "rm $SRC_PATH $SRC_XML" \
     "Could not remove $SRC_PATH or $SRC_XML on $DST_HOST"
 
 exit 0
diff --git a/vmm/kvm/save_linstor_un b/vmm/kvm/save_linstor_un
--- a/vmm/kvm/save_linstor_un
+++ b/vmm/kvm/save_linstor_un
@@ -71,7 +71,16 @@ STORAGE_POOL="${XPATH_ELEMENTS[j++]}"
 DISKLESS_POOL="${XPATH_ELEMENTS[j++]:-DfltDisklessStorPool}"
 ENCRYPTION="${XPATH_ELEMENTS[j++]}"
 
+if [ -n "$CHECKPOINT_AUTO_PLACE" ]; then
+    AUTO_PLACE="$CHECKPOINT_AUTO_PLACE"
+fi
+
+DST_RES="one-vm-${VM_ID}-checkpoint"
+DST_DEV="/dev/drbd/by-res/${DST_RES}/0"
+
 #-------------------------------------------------------------------------------
+# TM_MAD is not 'linstor_un'
+#-------------------------------------------------------------------------------P
 
 if [ "$TM_MAD" != "linstor_un" ]; then
     echo "$DRV_ACTION" | $SSH "$SRC_HOST" /var/tmp/one/vmm/kvm/save "$@"
@@ -79,20 +88,20 @@ if [ "$TM_MAD" != "linstor_un" ]; then
 fi
 
 #-------------------------------------------------------------------------------
+# TM_MAD is 'linstor_un'
+#-------------------------------------------------------------------------------
 
 source ${DRIVER_PATH}/../../etc/vmm/kvm/kvmrc
 source ${DRIVER_PATH}/../../datastore/libfs.sh
 source ${DRIVER_PATH}/../../etc/datastore/linstor_un/linstor_un.conf
 source ${DRIVER_PATH}/../../datastore/linstor_un/linstor_utils.sh
 
-if [ -n "$CHECKPOINT_AUTO_PLACE" ]; then
-    AUTO_PLACE="$CHECKPOINT_AUTO_PLACE"
-fi
 linstor_load_keys
 
-DST_RES="one-vm-${VM_ID}-checkpoint"
-DST_DEV="/dev/drbd/by-res/${DST_RES}/0"
+# Load cleanup trap
+trap linstor_cleanup_trap EXIT
 
+# Saving VM state to checkpoint file
 SAVE_CMD=$(cat <<EOT
 if [ -f "$DST_PATH" ]; then
     epoch=\$(date +%s)
@@ -109,10 +118,32 @@ EOT
 ssh_exec_and_log "$SRC_HOST" "$SAVE_CMD" \
     "Could not save $DEPLOY_ID to $DST_PATH on $SRC_HOST"
 
-ORIGINAL_SIZE_B="$($SSH $SRC_HOST $QEMU_IMG info $DST_PATH | $AWK -F'[ ()]+' '/^virtual size: / {print $4}')"
+ORIGINAL_SIZE_B="$($SSH $SRC_HOST $QEMU_IMG info $DST_PATH | \
+    $AWK -F'[ ()]+' '/^virtual size: / {print $4}')"
 
-linstor_deploy_volume "$DST_RES" "${ORIGINAL_SIZE_B}B"
+if [ -z "$ORIGINAL_SIZE_K" ]; then
+    error_message "Error getting $DST_PATH checkpoint size"
+    exit -1
+fi
 
+# Deploy new volume
+linstor_exec_and_log \
+    "resource-definition create $DST_RES" 
+LINSTOR_CLEANUP_RD+=" $DST_RES"
+linstor_exec_and_log \
+    "volume-definition create $VOL_CREATE_ARGS $DST_RES ${ORIGINAL_SIZE_B}B"
+linstor_exec_and_log \
+    "resource create $RES_CREATE_ARGS --storage-pool $STORAGE_POOL $NODE_LIST $DST_RES"
+
+# Attach diskless resource for DST_RES on SRC_HOST
+DST_RES_HOSTS=$(linstor_get_hosts_for_res "$DST_RES")
+if ! [[ " $DST_RES_HOSTS " =~ " $SRC_HOST " ]]; then
+    linstor_exec_and_log \
+        "resource create -s $DISKLESS_POOL $SRC_HOST $DST_RES"
+    LINSTOR_CLEANUP_RES+=" $SRC_HOST:$DST_RES"
+fi
+
+# Import checkpoint file
 IMPORT_CMD=$(cat <<EOF
     set -e -o pipefail
 
@@ -123,13 +154,8 @@ IMPORT_CMD=$(cat <<EOF
 EOF
 )
 
-linstor_attach_volume "$SRC_HOST" "$DST_RES" "$DISKLESS_POOL"
+ssh_exec_and_log "$SRC_HOST" "$IMPORT_CMD" \
+    "Error importing $DST_DEV on $SRC_HOST"
 
-ssh_exec_and_log    "$SRC_HOST" "$IMPORT_CMD" \
-                    "Error importing $DST_DEV on $SRC_HOST"
-
-linstor_detach_volume "$SRC_HOST" "$DST_RES" 1
-
-
-
+LINSTOR_CLEANUP_RD=
 exit 0
