linstor_exec: datastore: clone cp mkfs rm snap_delete snap_flatten snap_revert
Signed-off-by: kvaps <kvapss@gmail.com>

diff --git a/datastore/linstor_un/clone b/datastore/linstor_un/clone
--- a/datastore/linstor_un/clone
+++ b/datastore/linstor_un/clone
@@ -106,34 +106,49 @@ fi
 
 linstor_load_keys
 
+# Load cleanup trap
+trap linstor_cleanup_trap EXIT
+
 SAFE_DIRS=""
 
-VD_DATA="$($LINSTOR -m volume-definition list)"
-VD_STATUS=$?
-
-if [ "$VD_STATUS" != "0" ]; then
-    echo "$VD_DATA"
-    exit $VD_STATUS
-fi
-
-ORIGINAL_SIZE_K="$(linstor_vd_size "$VD_DATA" "$SRC_RES")"
+ORIGINAL_SIZE_K="$(linstor_vd_size "$SRC_RES")"
 if [ -z "$ORIGINAL_SIZE_K" ]; then
     error_message "Error getting $SRC_RES volume size"
     exit -1
 fi
 
-linstor_deploy_volume "$DST_RES" "${ORIGINAL_SIZE_K}K"
+# Deploy new volume
+linstor_exec_and_log \
+    "resource-definition create $DST_RES" 
+LINSTOR_CLEANUP_RD+=" $DST_RES"
+linstor_exec_and_log \
+    "volume-definition create $VOL_CREATE_ARGS $DST_RES ${ORIGINAL_SIZE_K}K"
+linstor_exec_and_log \
+    "resource create $RES_CREATE_ARGS --storage-pool $STORAGE_POOL $NODE_LIST $DST_RES"
 
-linstor_attach_volume "$SRC_HOST" "$SRC_RES" "$DISKLESS_POOL"
-linstor_attach_volume "$SRC_HOST" "$DST_RES" "$DISKLESS_POOL"
+SRC_RES_HOSTS=$(linstor_get_hosts_for_res "$SRC_RES")
+DST_RES_HOSTS=$(linstor_get_hosts_for_res "$DST_RES")
 
-ssh_exec_and_log "$SRC_HOST" "$QEMU_IMG convert -O raw $SRC $DST_DEV" \
-                 "Error cloning $SRC to $DST_DEV on $SRC_HOST"
+# Attach diskless resource for DST_RES on SRC_RES side
+if ! [[ " $SRC_RES_HOSTS " =~ " $SRC_HOST " ]]; then
+    linstor_exec_and_log \
+        "resource create -s $DISKLESS_POOL $SRC_HOST $SRC_RES"
+    LINSTOR_CLEANUP_RES+=" $SRC_HOST:$SRC_RES"
+fi
+if ! [[ " $DST_RES_HOSTS " =~ " $SRC_HOST " ]]; then
+    linstor_exec_and_log \
+        "resource create -s $DISKLESS_POOL $SRC_HOST $DST_RES"
+    LINSTOR_CLEANUP_RES+=" $SRC_HOST:$DST_RES"
+fi
 
-exec_and_log "$LINSTOR resource-definition set-property $DST_RES DrbdOptions/Net/allow-two-primaries yes" \
-    "Error setting allow-two-primaries=yes"
+# Clone image from SRC_RES to DST_RES
+ssh_exec_and_log "$SRC_HOST" \
+    "$QEMU_IMG convert -O raw $SRC $DST_DEV" \
+    "Error cloning $SRC to $DST_DEV on $SRC_HOST"
 
-linstor_detach_volume "$SRC_HOST" "$SRC_RES" 1
-linstor_detach_volume "$SRC_HOST" "$DST_RES" 1
+# Set allow-two-primaries=yes
+linstor_exec_and_log \
+    "resource-definition set-property $DST_RES DrbdOptions/Net/allow-two-primaries yes"
 
+LINSTOR_CLEANUP_RD=
 echo "$DST"
diff --git a/datastore/linstor_un/cp b/datastore/linstor_un/cp
--- a/datastore/linstor_un/cp
+++ b/datastore/linstor_un/cp
@@ -112,6 +112,9 @@ fi
 
 linstor_load_keys
 
+# Load cleanup trap
+trap linstor_cleanup_trap EXIT
+
 set_up_datastore "$BASE_PATH" "$RESTRICTED_DIRS" "$SAFE_DIRS"
 
 IMAGE_HASH=`generate_image_hash`
@@ -146,31 +149,49 @@ http://*|https://*)
 esac
 
 
-multiline_exec_and_log "set -e -o pipefail; $DUMP | $SSH $DST_HOST $DD of=$TMP_DST bs=${DD_BLOCK_SIZE:-64k}" \
-             "Error dumping $SRC to $DST_HOST:$TMP_DST"
+multiline_exec_and_log \
+    "set -e -o pipefail; $DUMP | $SSH $DST_HOST $DD of=$TMP_DST bs=${DD_BLOCK_SIZE:-64k}" \
+    "Error dumping $SRC to $DST_HOST:$TMP_DST"
 
 ORIGINAL_SIZE_B="$($SSH $DST_HOST $QEMU_IMG info $TMP_DST | $AWK -F'[ ()]+' '/^virtual size: / {print $4}')"
+if [ -z "$ORIGINAL_SIZE_B" ]; then
+    error_message "Error getting $TMP_DST size on $DST_HOST"
+    exit -1
+fi
 
-linstor_deploy_volume "$DST_RES" "${ORIGINAL_SIZE_B}B"
+# Deploy new volume
+linstor_exec_and_log \
+    "resource-definition create $DST_RES" 
+LINSTOR_CLEANUP_RD+=" $DST_RES"
+linstor_exec_and_log \
+    "volume-definition create $VOL_CREATE_ARGS $DST_RES ${ORIGINAL_SIZE_K}K"
+linstor_exec_and_log \
+    "resource create $RES_CREATE_ARGS --storage-pool $STORAGE_POOL $NODE_LIST $DST_RES"
 
+DST_RES_HOSTS=$(linstor_get_hosts_for_res "$DST_RES")
+
+# Attach diskless resource for DST_RES on DST_HOST
+if ! [[ " $DST_RES_HOSTS " =~ " $DST_HOST " ]]; then
+    linstor_exec_and_log \
+        "resource create -s $DISKLESS_POOL $DST_HOST $DST_RES"
+    LINSTOR_CLEANUP_RES+=" $DST_HOST:$DST_RES"
+fi
+
+# Import image
 IMPORT_CMD=$(cat <<EOF
     set -e -o pipefail
-
     $QEMU_IMG convert -O raw $TMP_DST $DST_DEV
-
     # remove original
     $RM -f $TMP_DST
 EOF
 )
 
-linstor_attach_volume "$DST_HOST" "$DST_RES" "$DISKLESS_POOL"
+ssh_exec_and_log "$DST_HOST" "$IMPORT_CMD" \
+    "Error importing $DST_DEV on $DST_HOST"
 
-ssh_exec_and_log    "$DST_HOST" "$IMPORT_CMD" \
-                    "Error importing $DST_DEV on $DST_HOST"
+# Set allow-two-primaries=yes
+linstor_exec_and_log \
+    "resource-definition set-property $DST_RES DrbdOptions/Net/allow-two-primaries yes"
 
-exec_and_log "$LINSTOR resource-definition set-property $DST_RES DrbdOptions/Net/allow-two-primaries yes" \
-    "Error setting allow-two-primaries=yes"
-
-linstor_detach_volume "$DST_HOST" "$DST_RES" 1
-
+LINSTOR_CLEANUP_RD=
 echo "$DST"
