better cleanup
Signed-off-by: kvaps <kvapss@gmail.com>

diff --git a/tm/linstor_un/clone b/tm/linstor_un/clone
--- a/tm/linstor_un/clone
+++ b/tm/linstor_un/clone
@@ -127,15 +127,15 @@ if [ -z "$STORAGE_POOL" ]; then
     error_message "Datastore template missing 'STORAGE_POOL' attribute."
     exit -1
 fi
-
 linstor_load_keys
-linstor_load_trap
+
+# Load cleanup trap
+trap linstor_cleanup_trap EXIT
 
 # Deploy new volume
 linstor_exec_and_log \
     "resource-definition create $DST_RES" 
-linstor_trap_and_log_no_error 0 \
-    "resource-definition delete $DST_RES --async"
+LINSTOR_CLEANUP_RD+="$DST_RES"
 linstor_exec_and_log \
     "volume-definition create $VOL_CREATE_ARGS $DST_RES ${SIZE}M"
 linstor_exec_and_log \
@@ -148,14 +148,12 @@ DST_RES_NODES=$(linstor_get_hosts_for_res "$DST_RES")
 if ! [[ " $SRC_RES_NODES " =~ " $SRC_HOST " ]]; then
     linstor_exec_and_log \
         "resource create -s $DISKLESS_POOL $SRC_HOST $SRC_RES"
-    linstor_trap_and_log_no_error 1 \
-        "resource delete $SRC_RES --async"
+    LINSTOR_CLEANUP_RES+="$SRC_HOST:$SRC_RES"
 fi
 if ! [[ " $DST_RES_NODES " =~ " $SRC_HOST " ]]; then
     linstor_exec_and_log \
         "resource create -s $DISKLESS_POOL $SRC_HOST $DST_RES"
-    linstor_trap_and_log_no_error 2 \
-        "resource delete $DST_RES --async"
+    LINSTOR_CLEANUP_RES+="$SRC_HOST:$DST_RES"
 fi
 
 # Clone image from SRC_RES to DST_RES
@@ -181,7 +179,5 @@ EOF
 ssh_exec_and_log "$DST_HOST" "$LINK_CMD" \
     "Error linking $DST_DEV to $DST_PATH on $DST_HOST"
 
-# Remove 'resource-definition delete' trap
-linstor_untrap 0
-
+LINSTOR_CLEANUP_RD=
 exit 0
