use blockcopy for more consistent copy

diff --git a/tm/linstor_un/cpds b/tm/linstor_un/cpds
--- a/tm/linstor_un/cpds
+++ b/tm/linstor_un/cpds
@@ -42,6 +42,7 @@ fi
 DRIVER_PATH=$(dirname $0)
 
 source $TMCOMMON
+source ${DRIVER_PATH}/../../etc/vmm/kvm/kvmrc
 source ${DRIVER_PATH}/../../datastore/libfs.sh
 source ${DRIVER_PATH}/../../etc/datastore/linstor_un/linstor_un.conf
 source ${DRIVER_PATH}/../../datastore/linstor_un/linstor_utils.sh
@@ -107,10 +108,14 @@ while IFS= read -r -d '' element; do
     XPATH_ELEMENTS[i++]="$element"
 done < <(onevm show -x $VM_ID| $XPATH \
                     /VM/DEPLOY_ID \
+                    /VM/LCM_STATE \
+                    /VM/TEMPLATE/DISK[DISK_ID=$DISK_ID]/TARGET \
                     /VM/TEMPLATE/DISK[DISK_ID=$DISK_ID]/SOURCE \
                     /VM/TEMPLATE/DISK[DISK_ID=$DISK_ID]/CLONE )
 
 DEPLOY_ID="${XPATH_ELEMENTS[j++]}"
+LCM_STATE="${XPATH_ELEMENTS[j++]}"
+DISK_TARGET="${XPATH_ELEMENTS[j++]}"
 SRC_DEV="${XPATH_ELEMENTS[j++]}"
 CLONE="${XPATH_ELEMENTS[j++]}"
 
@@ -126,6 +131,31 @@ ORIGINAL_SIZE_K="$(linstor_vd_size $SRC_RES)"
 if [ -z "$ORIGINAL_SIZE_K" ]; then
     error_message "Error getting $SRC_RES volume size"
     exit -1
+fi
+
+#-------------------------------------------------------------------------------
+# For current image of the running VMs, don't touch the image directly,
+# but export the content via blockcopy. If that's not possible (old QEMU),
+# domfsfreeze or suspend the domain before.
+#-------------------------------------------------------------------------------
+
+if [ "${LCM_STATE}" = '26' ] && [ "${SNAP_ID}" = '-1' ]; then
+    CPDS_CMD_EXPORT=$(cat <<EOF
+    if ! virsh -c ${LIBVIRT_URI} blockcopy ${DEPLOY_ID} ${DISK_TARGET} ${DST_DEV} --wait --finish; then
+        if virsh -c ${LIBVIRT_URI} domfsfreeze ${DEPLOY_ID}; then
+            trap "virsh -c ${LIBVIRT_URI} domfsthaw ${DEPLOY_ID}" EXIT TERM INT HUP
+        elif virsh -c ${LIBVIRT_URI} suspend ${DEPLOY_ID}; then
+            trap "virsh -c ${LIBVIRT_URI} resume ${DEPLOY_ID}" EXIT TERM INT HUP
+        else
+            echo "Could not domfsfreeze or suspend domain" >&2
+            exit 1
+        fi
+        ${QEMU_IMG} convert ${SRC_DEV} -O raw ${DST_DEV}
+    fi
+EOF
+)
+else
+    CPDS_CMD_EXPORT="${QEMU_IMG} convert ${SRC_DEV} -O raw ${DST_DEV}"
 fi
 
 #-------------------------------------------------------------------------------
@@ -153,7 +183,6 @@ linstor_exec_and_log \
 SRC_RES_HOSTS=$(linstor_get_hosts_for_res "$SRC_RES")
 DST_RES_HOSTS=$(linstor_get_hosts_for_res "$DST_RES")
 
-    
 if [ "$SNAP_ID" = "-1" ]; then
 
     # Attach diskless resource for DST_RES on SRC_HOST
@@ -165,7 +194,7 @@ if [ "$SNAP_ID" = "-1" ]; then
 
     # Clone image from TMP_RES to DST_RES
     ssh_exec_and_log \
-        "$SRC_HOST" "$QEMU_IMG convert -O raw $SRC_DEV $DST_DEV" \
+        "$SRC_HOST" "$CPDS_CMD_EXPORT" \
         "Error cloning $SRC_DEV to $DST_DEV on $SRC_HOST"
 
     LINSTOR_CLEANUP_RD=
