linstor_exec: tm: delete ln mkimage mv mvds postmigrate premigrate resize snap_create snap_create_live snap_delete snap_revert
Signed-off-by: kvaps <kvapss@gmail.com>

diff --git a/tm/linstor_un/mkimage b/tm/linstor_un/mkimage
--- a/tm/linstor_un/mkimage
+++ b/tm/linstor_un/mkimage
@@ -104,8 +104,27 @@ fi
 
 linstor_load_keys
 
-linstor_deploy_volume "$DST_RES" "${SIZE}M"
+# Load cleanup trap
+trap linstor_cleanup_trap EXIT
 
+# Deploy new volume
+linstor_exec_and_log \
+    "resource-definition create $DST_RES" 
+LINSTOR_CLEANUP_RD+=" $DST_RES"
+linstor_exec_and_log \
+    "volume-definition create $VOL_CREATE_ARGS $DST_RES ${SIZE}M"
+linstor_exec_and_log \
+    "resource create $RES_CREATE_ARGS --storage-pool $STORAGE_POOL $NODE_LIST $DST_RES"
+
+DST_RES_HOSTS=$(linstor_get_hosts_for_res "$DST_RES")
+
+# Attach diskless resource on destination host
+if ! [[ " $DST_RES_HOSTS " =~ " $DST_HOST " ]]; then
+    linstor_exec_and_log \
+        "resource create -s $DISKLESS_POOL $DST_HOST $DST_RES"
+fi
+
+# Link device on destination host
 LINK_CMD=$(cat <<EOF
     set -e -o pipefail
     mkdir -p $DST_DIR
@@ -114,17 +133,16 @@ LINK_CMD=$(cat <<EOF
 EOF
 )
 
-linstor_attach_volume "$DST_HOST" "$DST_RES" "$DISKLESS_POOL"
-
 ssh_exec_and_log "$DST_HOST" "$LINK_CMD" \
-                 "Error linking $DST_DEV to $DST_PATH on $DST_HOST"
+    "Error linking $DST_DEV to $DST_PATH on $DST_HOST"
 
-if [ "$FSTYPE" = "raw" ]; then
-    echo "$DST"
-    exit 0
+# Make filesystem on device
+if [ "$FSTYPE" != "raw" ]; then
+    MKFS_CMD=`mkfs_command $DST_PATH $FSTYPE $SIZE`
+    
+    ssh_exec_and_log "$DST_HOST" "$MKFS_CMD" \
+        "Unable to create filesystem $FSTYPE in $DST_HOST:$DST_PATH"
 fi
 
-MKFS_CMD=`mkfs_command $DST_PATH $FSTYPE $SIZE`
-
-ssh_exec_and_log "$DST_HOST" "$MKFS_CMD" \
-    "Unable to create filesystem $FSTYPE in $DST_HOST:$DST_PATH"
+LINSTOR_CLEANUP_RD=
+exit 0
diff --git a/tm/linstor_un/snap_revert b/tm/linstor_un/snap_revert
--- a/tm/linstor_un/snap_revert
+++ b/tm/linstor_un/snap_revert
@@ -66,6 +66,9 @@ DISKLESS_POOL="${XPATH_ELEMENTS[j++]:-DfltDisklessStorPool}"
 
 linstor_load_keys
 
+# Load cleanup trap
+trap linstor_cleanup_trap EXIT
+
 unset i j XPATH_ELEMENTS
 
 while IFS= read -r -d '' element; do
@@ -93,8 +96,11 @@ fi
 SNAPSHOT="snapshot-${SNAP_ID}"
 
 if [ "$SNAP_ID" = "$LAST_SNAP_ID" ]; then
-    exec_and_log "$LINSTOR snapshot rollback $SRC_RES $SNAPSHOT" \
-                 "Error reverting $SNAPSHOT for $SRC_RES"
+
+    # Rollback snapshot 
+    linstor_exec_and_log \
+        "snapshot rollback $SRC_RES $SNAPSHOT"
+
     exit 0
 fi
 
@@ -105,14 +111,26 @@ fi
 TMP_RES="${SRC_RES}-tmp"
 TMP_DEV="/dev/drbd/by-res/${TMP_RES}/0"
 
-linstor_deploy_snapshot "$SRC_RES" "$SNAPSHOT" "$TMP_RES"
+# Deploy snapshot as volume
+linstor_exec_and_log \
+    "resource-definition create $TMP_RES" 
+LINSTOR_CLEANUP_RD+=" $TMP_RES"
+linstor_exec_and_log \
+    "snapshot volume-definition restore --from-resource $SRC_RES --from-snapshot $SNAPSHOT --to-resource $TMP_RES"
+linstor_exec_and_log \
+    "snapshot resource restore --from-resource $SRC_RES --from-snapshot $SNAPSHOT --to-resource $TMP_RES"
 
 linstor_attach_volume "$SRC_HOST" "$TMP_RES" "$DISKLESS_POOL"
 
-ssh_exec_and_log "$SRC_HOST" "$QEMU_IMG convert -O raw $TMP_DEV $SRC_DEV" \
-                 "Error cloning $TMP_DEV to $SRC_DEV on $SRC_HOST"
+# Attach diskless resources on SRC_HOST
+if ! [[ " $TMP_RES_HOSTS " =~ " $SRC_HOST " ]]; then
+    linstor_exec_and_log \
+        "resource create -s $DISKLESS_POOL $SRC_HOST $TMP_RES"
+fi
 
-exec_and_log "$LINSTOR resource-definition delete $TMP_RES --async" \
-             "Error deleting $TMP_RES"
+# Clone image from TMP_RES to SRC_RES
+ssh_exec_and_log "$SRC_HOST" \
+    "$QEMU_IMG convert -O raw $TMP_DEV $SRC_DEV" \
+    "Error cloning $TMP_DEV to $SRC_DEV on $SRC_HOST"
 
 exit 0
